Different operating system
bizflycloud/bizfly-backup pull request #99
Opened 2021-07-22 16:09 UTC by dactoankmapydev

2021-07-23 01:43 UTC, ducpx approved these changes

2021-07-23 02:56 UTC, greatbn requested changes
Check my comments

2021-07-23 02:56 UTC, greatbn commented on pkg/backupapi/file_test.go
> +// func TestClient_GetItemLatest(t *testing.T) {
If you don't use these code, please remove.

2021-07-23 02:56 UTC, greatbn commented on pkg/backupapi/volume.go
> +	"github.com/aws/aws-sdk-go/aws/awserr"
group import.

2021-07-23 02:56 UTC, greatbn commented on pkg/backupapi/volume.go
> +func (c *Client) GetObject(volume volume.StorageVolume, key string, restoreKey *AuthRestore) ([]byte, error) {
I think we should comment for these exported function. It's doc string.

2021-07-23 02:56 UTC, greatbn commented on pkg/volume/s3/s3.go
> +	"github.com/bizflycloud/bizfly-backup/pkg/backupapi"
group import.

2021-07-23 02:56 UTC, greatbn commented on pkg/volume/s3/s3.go
> +		fmt.Println("Bad credentials", err)
log or print ?

2021-07-23 02:56 UTC, greatbn commented on pkg/volume/s3/s3.go
> +	//cred := credentials.NewStaticCredentials(accessKey, secretKey, token)
do we need this line ?

2021-07-23 02:56 UTC, greatbn commented on pkg/volume/s3/s3.go
> +				s3.logger.Info("====== Put object one more time =============")
Why do you use `===`

2021-07-24 02:32 UTC, greatbn requested changes
Please fix error of CI.

2021-08-19 02:57 UTC, greatbn approved these changes
LGTM

2021-08-19 02:58 UTC, merged